sudo: required
language: java
jdk:
- openjdk11
before_script:
- chmod +x gradlew
script:
  #  static code analysis
  #  run unit test for automation framework
  - ./gradlew clean check

  #  run bdd test
  - ./gradlew clean runFeatures
before_install:
- openssl aes-256-cbc -K $encrypted_6fcb997bf455_key -iv $encrypted_6fcb997bf455_iv
  -in config.json.enc -out config.json -d
